from pathlib import Path
import json, html

ROOT=Path(__file__).parent
DIST=ROOT/'dist'
BASE='https://www.tabacluxe.lu'
LANGS=['en','fr','de','nl','es','it','pt','pl','ro','lb']
NAMES={'en':'English','fr':'Français','de':'Deutsch','nl':'Nederlands','es':'Español','it':'Italiano','pt':'Português','pl':'Polski','ro':'Română','lb':'Lëtzebuergesch'}
T={
'en':{'home':'Home','catalog':'Catalogue','tobacco':'Tobacco','alcohol':'Alcohol & Drinks','about':'About Us','contact':'Contact','enquiry':'Enquiry','hero':'Premium Brands. Wholesale Confidence.','sub':'Tobacco, alcohol and more for your business. Trade catalogue for professional buyers across Europe.','browse':'Browse Our Catalogue','featured':'Featured Products','add':'Add to Enquiry','trade':'Trade Only','markets':'Supplying Businesses Across Europe','search':'Search products','all':'All categories','about_h':'European wholesale, presented differently.','about_p':'Tabac Luxe is a Luxembourg-based B2B catalogue for professional trade enquiries across Europe. Products are displayed for browsing and enquiry only; no online checkout or payment is offered.','contact_h':'Speak to Tabac Luxe','contact_p':'Build an enquiry list and send it by WhatsApp or email. Our team will discuss availability, trade requirements and next steps directly.','seo':'tobacco wholesaler Luxembourg, cigarette wholesale Europe, alcohol wholesaler Luxembourg, spirits wholesale Europe, B2B tobacco supplier'},
'fr':{'home':'Accueil','catalog':'Catalogue','tobacco':'Tabac','alcohol':'Alcools & Boissons','about':'À propos','contact':'Contact','enquiry':'Demande','hero':'Marques Premium. Confiance Wholesale.','sub':'Tabac, alcools et plus pour votre entreprise. Catalogue professionnel pour acheteurs en Europe.','browse':'Voir le catalogue','featured':'Produits en vedette','add':'Ajouter à la demande','trade':'Réservé aux professionnels','markets':'Fournisseur B2B en Europe','search':'Rechercher des produits','all':'Toutes catégories','about_h':'Le wholesale européen, présenté avec élégance.','about_p':'Tabac Luxe est un catalogue B2B basé au Luxembourg destiné aux demandes commerciales professionnelles en Europe. Aucun paiement ni achat en ligne.','contact_h':'Contacter Tabac Luxe','contact_p':'Créez votre liste de demande puis envoyez-la par WhatsApp ou e-mail.','seo':'grossiste tabac Luxembourg, grossiste cigarettes Europe, grossiste alcool Luxembourg, fournisseur spiritueux Europe, fournisseur tabac B2B'},
'de':{'home':'Startseite','catalog':'Katalog','tobacco':'Tabak','alcohol':'Alkohol & Getränke','about':'Über uns','contact':'Kontakt','enquiry':'Anfrage','hero':'Premium-Marken. Großhandel mit Vertrauen.','sub':'Tabak, Alkohol und mehr für Ihr Unternehmen. B2B-Katalog für professionelle Käufer in Europa.','browse':'Katalog ansehen','featured':'Ausgewählte Produkte','add':'Zur Anfrage','trade':'Nur für Gewerbe','markets':'B2B-Lieferung in Europa','search':'Produkte suchen','all':'Alle Kategorien','about_h':'Europäischer Großhandel, hochwertig präsentiert.','about_p':'Tabac Luxe ist ein in Luxemburg ansässiger B2B-Katalog für professionelle Handelsanfragen in Europa. Kein Online-Kauf und keine Online-Zahlung.','contact_h':'Tabac Luxe kontaktieren','contact_p':'Stellen Sie Ihre Anfrageliste zusammen und senden Sie sie per WhatsApp oder E-Mail.','seo':'Tabak Großhandel Luxemburg, Zigaretten Großhandel Europa, Alkohol Großhandel Luxemburg, Spirituosen Großhandel Europa, B2B Tabak Lieferant'},
'nl':{'home':'Home','catalog':'Catalogus','tobacco':'Tabak','alcohol':'Alcohol & Dranken','about':'Over ons','contact':'Contact','enquiry':'Aanvraag','hero':'Premium merken. Vertrouwen in groothandel.','sub':'Tabak, alcohol en meer voor uw bedrijf. B2B-catalogus voor professionele kopers in Europa.','browse':'Bekijk catalogus','featured':'Uitgelichte producten','add':'Toevoegen aan aanvraag','trade':'Alleen voor handel','markets':'B2B-levering door Europa','search':'Producten zoeken','all':'Alle categorieën','about_h':'Europese groothandel, luxueus gepresenteerd.','about_p':'Tabac Luxe is een Luxemburgse B2B-catalogus voor professionele handelsaanvragen in Europa. Geen online aankoop of betaling.','contact_h':'Contacteer Tabac Luxe','contact_p':'Stel uw aanvraaglijst samen en verstuur die via WhatsApp of e-mail.','seo':'tabak groothandel Luxemburg, sigaretten groothandel Europa, alcohol groothandel Luxemburg, sterke drank groothandel Europa, B2B tabak leverancier'},
'es':{'home':'Inicio','catalog':'Catálogo','tobacco':'Tabaco','alcohol':'Alcohol & Bebidas','about':'Nosotros','contact':'Contacto','enquiry':'Consulta','hero':'Marcas Premium. Confianza Mayorista.','sub':'Tabaco, alcohol y más para su negocio. Catálogo B2B para compradores profesionales en Europa.','browse':'Ver catálogo','featured':'Productos destacados','add':'Añadir a consulta','trade':'Solo profesionales','markets':'Suministro B2B en Europa','search':'Buscar productos','all':'Todas las categorías','about_h':'Mayorista europeo con presentación de lujo.','about_p':'Tabac Luxe es un catálogo B2B con sede en Luxemburgo para consultas comerciales profesionales en Europa. Sin compra ni pago online.','contact_h':'Contactar con Tabac Luxe','contact_p':'Cree su lista de consulta y envíela por WhatsApp o correo electrónico.','seo':'mayorista tabaco Luxemburgo, mayorista cigarrillos Europa, mayorista alcohol Luxemburgo, mayorista bebidas espirituosas Europa, proveedor tabaco B2B'},
'it':{'home':'Home','catalog':'Catalogo','tobacco':'Tabacco','alcohol':'Alcol & Bevande','about':'Chi siamo','contact':'Contatti','enquiry':'Richiesta','hero':'Marchi Premium. Fiducia all’ingrosso.','sub':'Tabacco, alcol e altro per la tua attività. Catalogo B2B per acquirenti professionali in Europa.','browse':'Sfoglia il catalogo','featured':'Prodotti in evidenza','add':'Aggiungi alla richiesta','trade':'Solo operatori','markets':'Fornitura B2B in Europa','search':'Cerca prodotti','all':'Tutte le categorie','about_h':'Ingrosso europeo, presentato con lusso.','about_p':'Tabac Luxe è un catalogo B2B con sede in Lussemburgo per richieste commerciali professionali in Europa. Nessun acquisto o pagamento online.','contact_h':'Contatta Tabac Luxe','contact_p':'Crea la tua lista e inviala tramite WhatsApp o e-mail.','seo':'grossista tabacco Lussemburgo, grossista sigarette Europa, grossista alcol Lussemburgo, grossista spirits Europa, fornitore tabacco B2B'},
'pt':{'home':'Início','catalog':'Catálogo','tobacco':'Tabaco','alcohol':'Álcool & Bebidas','about':'Sobre nós','contact':'Contacto','enquiry':'Pedido','hero':'Marcas Premium. Confiança no Atacado.','sub':'Tabaco, álcool e mais para o seu negócio. Catálogo B2B para compradores profissionais na Europa.','browse':'Ver catálogo','featured':'Produtos em destaque','add':'Adicionar ao pedido','trade':'Apenas profissionais','markets':'Fornecimento B2B na Europa','search':'Pesquisar produtos','all':'Todas as categorias','about_h':'Atacado europeu com apresentação premium.','about_p':'Tabac Luxe é um catálogo B2B sediado no Luxemburgo para consultas profissionais na Europa. Sem compra ou pagamento online.','contact_h':'Contactar Tabac Luxe','contact_p':'Crie a lista de pedido e envie por WhatsApp ou e-mail.','seo':'grossista tabaco Luxemburgo, grossista cigarros Europa, grossista álcool Luxemburgo, grossista bebidas espirituosas Europa, fornecedor tabaco B2B'},
'pl':{'home':'Start','catalog':'Katalog','tobacco':'Tytoń','alcohol':'Alkohol i Napoje','about':'O nas','contact':'Kontakt','enquiry':'Zapytanie','hero':'Marki Premium. Zaufanie w Hurcie.','sub':'Tytoń, alkohol i więcej dla Twojej firmy. Katalog B2B dla profesjonalnych kupujących w Europie.','browse':'Zobacz katalog','featured':'Polecane produkty','add':'Dodaj do zapytania','trade':'Tylko handel','markets':'Dostawy B2B w Europie','search':'Szukaj produktów','all':'Wszystkie kategorie','about_h':'Europejski hurt w luksusowym wydaniu.','about_p':'Tabac Luxe to luksemburski katalog B2B dla profesjonalnych zapytań handlowych w Europie. Bez zakupu i płatności online.','contact_h':'Skontaktuj się z Tabac Luxe','contact_p':'Utwórz listę zapytania i wyślij ją przez WhatsApp lub e-mail.','seo':'hurtownia tytoniu Luksemburg, hurtownia papierosów Europa, hurtownia alkoholu Luksemburg, hurtownia alkoholi mocnych Europa, dostawca tytoniu B2B'},
'ro':{'home':'Acasă','catalog':'Catalog','tobacco':'Tutun','alcohol':'Alcool & Băuturi','about':'Despre noi','contact':'Contact','enquiry':'Solicitare','hero':'Mărci Premium. Încredere Wholesale.','sub':'Tutun, alcool și mai mult pentru afacerea dvs. Catalog B2B pentru cumpărători profesioniști din Europa.','browse':'Vezi catalogul','featured':'Produse recomandate','add':'Adaugă la solicitare','trade':'Doar pentru comercianți','markets':'Furnizare B2B în Europa','search':'Caută produse','all':'Toate categoriile','about_h':'Wholesale european, prezentat premium.','about_p':'Tabac Luxe este un catalog B2B cu sediul în Luxemburg pentru solicitări comerciale profesionale în Europa. Fără cumpărare sau plată online.','contact_h':'Contactați Tabac Luxe','contact_p':'Creați lista de solicitare și trimiteți-o prin WhatsApp sau e-mail.','seo':'angro tutun Luxemburg, angro țigări Europa, angro alcool Luxemburg, distribuitor băuturi spirtoase Europa, furnizor tutun B2B'},
'lb':{'home':'Startsäit','catalog':'Katalog','tobacco':'Tubak','alcohol':'Alkohol & Gedrénks','about':'Iwwer eis','contact':'Kontakt','enquiry':'Ufro','hero':'Premium Marken. Wholesale Vertrauen.','sub':'Tubak, Alkohol a méi fir Äert Geschäft. B2B-Katalog fir professionell Keefer an Europa.','browse':'Katalog kucken','featured':'Ausgewielte Produiten','add':'Bei d’Ufro','trade':'Nëmme fir Handel','markets':'B2B Liwwerung an Europa','search':'Produite sichen','all':'All Kategorien','about_h':'Europäesche Grousshandel, luxuriéis presentéiert.','about_p':'Tabac Luxe ass e B2B-Katalog zu Lëtzebuerg fir professionell Handelsufroen an Europa. Kee Online-Kaf a keng Online-Bezuelung.','contact_h':'Tabac Luxe kontaktéieren','contact_p':'Setzt Är Ufro-Lëscht zesummen a schéckt se iwwer WhatsApp oder E-Mail.','seo':'Tubak Grousshandel Lëtzebuerg, Zigaretten Grousshandel Europa, Alkohol Grousshandel Lëtzebuerg, Spirituosen Grousshandel Europa, B2B Tubak Fournisseur'}
}
CATS=['cigarettes','rolling-tobacco','cigars','shisha','beer','wine','whisky','vodka','gin','rum','brandy','accessories']
CATN={'cigarettes':'Cigarettes','rolling-tobacco':'Rolling Tobacco','cigars':'Cigars','shisha':'Shisha Tobacco','beer':'Beer','wine':'Wine','whisky':'Whisky','vodka':'Vodka','gin':'Gin','rum':'Rum','brandy':'Brandy','accessories':'Accessories'}
products=json.loads((ROOT/'src/products.json').read_text())

def esc(s): return html.escape(str(s), quote=True)
def path_url(lang,rel=''): return f'{BASE}/{lang}/'+rel.lstrip('/')
def alternates(rel=''):
    return ''.join(f'<link rel="alternate" hreflang="{l}" href="{path_url(l,rel)}">' for l in LANGS)+f'<link rel="alternate" hreflang="x-default" href="{path_url("en",rel)}">'
def nav(lang):
    t=T[lang]
    links=''.join(f'<a href="/{l}/">{NAMES[l]}</a>' for l in LANGS)
    return f'<div class="top"><div class="wrap topin">{links}</div></div><div class="nav"><div class="wrap navin"><a class="brand" href="/{lang}/">TABAC LUXE<small>TOBACCO & ALCOHOL WHOLESALE</small></a><div class="menu"><a href="/{lang}/">{t["home"]}</a><a href="/{lang}/catalog/">{t["catalog"]}</a><a href="/{lang}/tobacco/">{t["tobacco"]}</a><a href="/{lang}/alcohol/">{t["alcohol"]}</a><a href="/{lang}/about/">{t["about"]}</a><a href="/{lang}/contact/">{t["contact"]}</a></div><div class="tools"><button class="pill" data-open-cart>{t["enquiry"]} (<span data-count>0</span>)</button></div></div></div>'
def drawer(lang):
    return f'<aside id="drawer" class="drawer"><div class="drawerhead"><b>{T[lang]["enquiry"]}</b><button class="btn" data-close-cart>×</button></div><div id="cartBody" class="drawerbody"></div><div class="drawerfoot"><button class="btn gold" onclick="sendWA()">WhatsApp</button><button class="btn" onclick="sendMail()">Email</button></div></aside><a class="float-wa" href="javascript:sendWA()">WA</a><div class="toast"></div>'
def product_card(lang,p):
    return f'<article class="product" data-category="{esc(p["category"])}"><a class="prodimg" href="/{lang}/product/{p["slug"]}/"><div class="pack">{esc(p["brand"])}</div></a><div class="pbody"><div class="pbrand">{esc(p["brand"])}</div><h3><a href="/{lang}/product/{p["slug"]}/">{esc(p["name"])}</a></h3><div class="meta">{esc(p["size"])}</div><div class="price">{esc(p["price"])}</div><button class="btn" data-add data-slug="{esc(p["slug"])}" data-name="{esc(p["name"])}" data-size="{esc(p["size"])}" data-price="{esc(p["price"])}">{T[lang]["add"]}</button></div></article>'
def layout(lang,title,desc,rel,body):
    t=T[lang]; canonical=path_url(lang,rel)
    schema='{"@context":"https://schema.org","@type":"Organization","name":"Tabac Luxe","url":"'+BASE+'"}'
    return f'<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(desc)}"><meta name="keywords" content="{esc(t["seo"])}"><link rel="canonical" href="{canonical}">{alternates(rel)}<link rel="stylesheet" href="/assets/style.css"><script type="application/ld+json">{schema}</script></head><body>{nav(lang)}{body}{footer(lang)}{drawer(lang)}<script src="/assets/app.js"></script></body></html>'
def footer(lang):
    t=T[lang]
    return f'<footer class="footer"><div class="wrap footgrid"><div><div class="brand">TABAC LUXE<small>TOBACCO & ALCOHOL WHOLESALE</small></div><p>Luxembourg · Europe</p></div><div><h4>{t["catalog"]}</h4><ul><li><a href="/{lang}/tobacco/">{t["tobacco"]}</a></li><li><a href="/{lang}/alcohol/">{t["alcohol"]}</a></li></ul></div><div><h4>{t["about"]}</h4><ul><li><a href="/{lang}/about/">{t["about"]}</a></li><li><a href="/{lang}/contact/">{t["contact"]}</a></li></ul></div><div><h4>Europe</h4><p>{t["markets"]}</p></div></div><div class="wrap legal">© 2026 Tabac Luxe. B2B catalogue. No online checkout or payment.</div></footer>'
def write(rel,content):
    p=DIST/rel; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(content,encoding='utf-8')

def grid(ps,lang): return '<div class="product-grid">'+''.join(product_card(lang,p) for p in ps)+'</div>'

DIST.mkdir(exist_ok=True)
# Copy text assets already versioned in repository.
assets=DIST/'assets'; assets.mkdir(exist_ok=True)
# Hero SVG generated as text-only asset for GitHub-safe deployment.
(assets/'luxury-hero.svg').write_text('''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 900"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#080706"/><stop offset=".55" stop-color="#3a2413"/><stop offset="1" stop-color="#0d0b09"/></linearGradient><radialGradient id="r"><stop stop-color="#b97c31" stop-opacity=".55"/><stop offset="1" stop-color="#000" stop-opacity="0"/></radialGradient></defs><rect width="1600" height="900" fill="url(#g)"/><circle cx="1230" cy="340" r="420" fill="url(#r)"/><rect x="1120" y="210" width="120" height="430" rx="35" fill="#6e330f"/><rect x="1270" y="170" width="140" height="470" rx="42" fill="#8a4f1f"/><rect x="930" y="300" width="130" height="320" rx="8" fill="#c9b89a"/><rect x="930" y="300" width="130" height="115" fill="#b51220"/><text x="995" y="470" text-anchor="middle" font-family="serif" font-size="23" fill="#111">TABAC</text></svg>''',encoding='utf-8')
# Patch deployed stylesheet reference if needed.
css=(ROOT/'dist/assets/style.css')
if css.exists():
    s=css.read_text(); s=s.replace("url('/assets/luxury-hero.jpg')","url('/assets/luxury-hero.svg')"); (assets/'style.css').write_text(s)
# Copy JS from repository working tree if present.
for n in ['app.js','admin.js']:
    p=ROOT/'dist/assets'/n
    if p.exists(): (assets/n).write_text(p.read_text())

all_urls=[]
for lang in LANGS:
    t=T[lang]
    hero=f'<section class="hero" style="background:linear-gradient(90deg,rgba(0,0,0,.95),rgba(0,0,0,.65),rgba(0,0,0,.25)),url(/assets/luxury-hero.svg) center/cover"><div class="wrap"><div class="eyebrow">Luxembourg · Europe · {t["trade"]}</div><h1>{t["hero"]}</h1><p>{t["sub"]}</p><div class="actions"><a class="btn gold" href="/{lang}/catalog/">{t["browse"]}</a><a class="btn" href="/{lang}/contact/">{t["contact"]}</a></div><div class="trust"><span>Premium Brands</span><span>Trade Enquiries</span><span>Across Europe</span></div></div></section>'
    cats='<section class="category-strip"><div class="wrap categories">'+''.join(f'<a class="catcard" href="/{lang}/category/{c}/"><h3>{CATN[c]}</h3><span>{t["browse"]} →</span></a>' for c in ['cigarettes','whisky','vodka','beer'])+'</div></section>'
    body=hero+cats+f'<section class="section white"><div class="wrap"><div class="head"><div><div class="eyebrow">TABAC LUXE</div><h2>{t["featured"]}</h2></div><p>{t["markets"]}</p></div>{grid(products[:10],lang)}</div></section><section class="featureband"><div class="wrap featuregrid"><div><strong>Wide Range</strong><small>Tobacco, Alcohol & Accessories</small></div><div><strong>Trade Enquiries</strong><small>No online checkout</small></div><div><strong>Across Europe</strong><small>Cross-border B2B catalogue</small></div><div><strong>WhatsApp</strong><small>Fast enquiry handoff</small></div></div></section>'
    write(f'{lang}/index.html',layout(lang,f'Tabac Luxe | {t["hero"]}',t['sub'],'',body)); all_urls.append(path_url(lang,''))
    body=f'<section class="cataloghero"><div class="wrap"><div class="eyebrow">TABAC LUXE</div><h1>{t["catalog"]}</h1><p>{t["sub"]}</p></div></section><section class="section"><div class="wrap"><div class="filters"><input id="q" placeholder="{t["search"]}"><select id="catFilter"><option value="">{t["all"]}</option>'+''.join(f'<option value="{c}">{CATN[c]}</option>' for c in CATS)+'</select></div>'+grid(products,lang)+'</div></section>'
    write(f'{lang}/catalog/index.html',layout(lang,f'{t["catalog"]} | Tabac Luxe',t['sub'],'catalog/',body)); all_urls.append(path_url(lang,'catalog/'))
    for section,types in [('tobacco',{'Tobacco'}),('alcohol',{'Alcohol & Drinks'})]:
        ps=[p for p in products if p['type'] in types]
        h=t[section]
        b=f'<section class="cataloghero"><div class="wrap"><div class="eyebrow">B2B · Luxembourg</div><h1>{h}</h1><p>{t["seo"]}</p></div></section><section class="section"><div class="wrap">{grid(ps,lang)}</div></section>'
        write(f'{lang}/{section}/index.html',layout(lang,f'{h} Wholesale Luxembourg | Tabac Luxe',t['seo'],f'{section}/',b)); all_urls.append(path_url(lang,f'{section}/'))
    for rel,h,ptext in [('about/',t['about_h'],t['about_p']),('contact/',t['contact_h'],t['contact_p'])]:
        b=f'<section class="cataloghero"><div class="wrap"><div class="eyebrow">TABAC LUXE</div><h1>{h}</h1></div></section><section class="section white"><div class="wrap content"><p>{ptext}</p><p>{t["seo"]}</p><div class="actions"><button class="btn gold" onclick="sendWA()">WhatsApp</button><button class="btn" onclick="sendMail()">Email</button></div></div></section>'
        write(f'{lang}/{rel}index.html',layout(lang,f'{h} | Tabac Luxe',ptext,rel,b)); all_urls.append(path_url(lang,rel))
    for c in CATS:
        ps=[p for p in products if p['category']==c]
        b=f'<section class="cataloghero"><div class="wrap"><div class="eyebrow">B2B Wholesale · Luxembourg</div><h1>{CATN[c]}</h1><p>{t["seo"]}</p></div></section><section class="section"><div class="wrap">{grid(ps,lang) if ps else "<p>Trade availability on request.</p>"}</div></section>'
        rel=f'category/{c}/'; write(f'{lang}/{rel}index.html',layout(lang,f'{CATN[c]} Wholesale Luxembourg | Tabac Luxe',t['seo'],rel,b)); all_urls.append(path_url(lang,rel))
    for p in products:
        rel=f'product/{p["slug"]}/'; desc=f'{p["name"]} {p["size"]}. B2B trade catalogue from Tabac Luxe Luxembourg. Enquire by WhatsApp or email; no online checkout.'
        b=f'<section class="cataloghero"><div class="wrap breadcrumb"><a href="/{lang}/catalog/">{t["catalog"]}</a> / {esc(p["name"])}</div><div class="wrap"><div class="eyebrow">{esc(p["brand"])}</div><h1>{esc(p["name"])}</h1><p>{esc(p["size"])}</p></div></section><section class="section white"><div class="wrap"><div class="product" data-category="{esc(p["category"])}" style="max-width:520px"><div class="prodimg"><div class="pack">{esc(p["brand"])}</div></div><div class="pbody"><div class="pbrand">{esc(p["brand"])}</div><h3>{esc(p["name"])}</h3><div class="meta">{esc(p["size"])}</div><div class="price">{esc(p["price"])}</div><button class="btn gold" data-add data-slug="{esc(p["slug"])}" data-name="{esc(p["name"])}" data-size="{esc(p["size"])}" data-price="{esc(p["price"])}">{t["add"]}</button></div></div><div class="content"><h2>Trade product information</h2><p>{esc(desc)}</p><p>{t["seo"]}</p></div></div></section>'
        write(f'{lang}/{rel}index.html',layout(lang,f'{p["name"]} Wholesale | Tabac Luxe Luxembourg',desc,rel,b)); all_urls.append(path_url(lang,rel))

write('index.html','<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=/en/"><link rel="canonical" href="'+BASE+'/en/">')
write('404.html','<!doctype html><meta charset="utf-8"><title>Tabac Luxe</title><h1>Page not found</h1><a href="/en/">Tabac Luxe</a>')
write('.nojekyll','')
write('robots.txt',f'User-agent: *\nAllow: /\nSitemap: {BASE}/sitemap.xml\n')
xml='<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{u}</loc></url>' for u in all_urls)+'</urlset>'
write('sitemap.xml',xml)
# Admin data and page
(DIST/'src-data').mkdir(exist_ok=True); (DIST/'src-data/products.json').write_text(json.dumps(products,ensure_ascii=False,indent=2),encoding='utf-8')
admin='<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tabac Luxe Catalogue Manager</title><link rel="stylesheet" href="/assets/style.css"><main class="admin"><h1>Tabac Luxe Catalogue Manager</h1><p class="note">Edit/import/export catalogue JSON here. Publish changes by replacing src/products.json and committing.</p><div class="adminbar"><input type="file" id="file" accept="application/json"><button onclick="download()">Download JSON</button><button onclick="csv()">Download CSV</button></div><table><thead><tr><th>#</th><th>Name</th><th>Category</th><th>Size</th><th>Price</th><th></th></tr></thead><tbody id="rows"></tbody></table></main><script src="/assets/admin.js"></script>'
write('admin/index.html',admin)
print(f'Generated {len(all_urls)} indexable URLs across {len(LANGS)} languages in {DIST}')
